use std::{iter::FusedIterator, slice, sync::Arc};

use percent_encoding::percent_decode_str;
use topcoat_core::context::{Cx, request_context};

/// A typed view of a path parameter declared by the `path_param!` macro.
///
/// This trait is implemented by the macro and is not meant to be implemented by
/// hand. Read the value with the [`path_param`] free function rather than
/// calling the trait method directly.
pub trait PathParam {
    /// The value produced for a request bound to lifetime `'cx`.
    ///
    /// The output depends on whether the declaration is parsed and whether it
    /// captures one segment or the rest of the path. See the `path_param!`
    /// macro for each form.
    type Output<'cx>;

    /// Reads the parameter from the request `cx` belongs to.
    ///
    /// Call [`path_param::<T>(cx)`](path_param) instead: this method is sealed
    /// behind [`PathParamSealed`] and cannot be invoked directly.
    #[doc(hidden)]
    #[track_caller]
    fn path_param(cx: &Cx, _: PathParamSealed) -> Self::Output<'_>;
}

/// Reads a typed path parameter from the matched route's path.
///
/// See the `path_param!` macro for details.
///
/// # Panics
///
/// Panics if the matched route's path does not capture the parameter.
#[inline]
#[must_use]
#[track_caller]
pub fn path_param<T: PathParam + ?Sized>(cx: &Cx) -> T::Output<'_> {
    T::path_param(cx, PathParamSealed::new())
}

/// Reads the raw path parameters captured by the matched route.
#[inline]
#[must_use]
#[track_caller]
pub fn raw_path_params(cx: &Cx) -> &RawPathParams {
    request_context::<RawPathParams>(cx)
}

/// Reads one decoded segment for an implementation generated by
/// the `path_param!` macro.
#[doc(hidden)]
#[must_use]
#[track_caller]
pub fn path_param_segment<'cx>(cx: &'cx Cx, name: &str) -> &'cx str {
    match raw_path_params(cx).find(name) {
        Some(RawPathParamValue::Segment(value)) => value,
        Some(RawPathParamValue::CatchAll { .. }) => {
            panic!("path parameter \"{name}\" captured multiple segments")
        }
        None => panic!("path parameter \"{name}\" was not found in request path"),
    }
}

/// Reads decoded catch-all segments for an implementation generated by
/// the `path_param!` macro.
#[doc(hidden)]
#[track_caller]
pub fn path_param_segments<'cx>(cx: &'cx Cx, name: &str) -> CatchAllSegments<'cx> {
    match raw_path_params(cx).find(name) {
        Some(RawPathParamValue::CatchAll { segments, .. }) => CatchAllSegments::new(segments),
        Some(RawPathParamValue::Segment(_)) => {
            panic!("path parameter \"{name}\" captured one segment")
        }
        None => panic!("path parameter \"{name}\" was not found in request path"),
    }
}

/// Decoded segments captured by a catch-all path parameter.
///
/// This iterator yields one `&str` per URL segment. An encoded slash remains
/// part of its segment instead of becoming a separator.
#[derive(Debug, Clone)]
#[must_use = "iterators are lazy and do nothing unless consumed"]
pub struct CatchAllSegments<'params> {
    inner: slice::Iter<'params, Box<str>>,
}

impl<'params> CatchAllSegments<'params> {
    fn new(segments: &'params [Box<str>]) -> Self {
        Self {
            inner: segments.iter(),
        }
    }
}

impl<'params> Iterator for CatchAllSegments<'params> {
    type Item = &'params str;

    fn next(&mut self) -> Option<Self::Item> {
        self.inner.next().map(Box::as_ref)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        self.inner.size_hint()
    }
}

impl DoubleEndedIterator for CatchAllSegments<'_> {
    fn next_back(&mut self) -> Option<Self::Item> {
        self.inner.next_back().map(Box::as_ref)
    }
}

impl ExactSizeIterator for CatchAllSegments<'_> {}
impl FusedIterator for CatchAllSegments<'_> {}

/// The path parameters captured from the matched route.
///
/// Iterating over a reference yields each `(name, value)` pair as string
/// slices. Single-segment values are percent-decoded. Catch-all values keep the
/// encoded tail, including its `/` separators. Declare a catch-all with
/// `path_param!` and read it with [`path_param`] to get decoded segments.
#[derive(Debug, Clone, Default)]
pub struct RawPathParams(Vec<RawPathParam>);

impl RawPathParams {
    /// Captures the parameters of a route match.
    pub(crate) fn from_pairs<'pairs>(
        pairs: impl IntoIterator<Item = (RawPathParamSpec, &'pairs str)>,
    ) -> Self {
        Self(
            pairs
                .into_iter()
                .map(|(param, value)| RawPathParam {
                    name: param.name,
                    value: match param.kind {
                        RawPathParamKind::Segment => RawPathParamValue::Segment(decode(value)),
                        RawPathParamKind::CatchAll => RawPathParamValue::CatchAll {
                            raw: value.to_owned().into_boxed_str(),
                            segments: value.split('/').map(decode).collect(),
                        },
                    },
                })
                .collect(),
        )
    }

    fn find(&self, name: &str) -> Option<&RawPathParamValue> {
        self.0
            .iter()
            .find_map(|param| (param.name.as_ref() == name).then_some(&param.value))
    }

    /// Iterates over each `(name, value)` pair as string slices.
    pub fn iter(&self) -> RawPathParamsIter<'_> {
        RawPathParamsIter {
            inner: self.0.iter(),
        }
    }
}

impl<'params> IntoIterator for &'params RawPathParams {
    type Item = (&'params str, &'params str);
    type IntoIter = RawPathParamsIter<'params>;

    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

/// An iterator over the raw path parameters captured by a route.
#[derive(Debug, Clone)]
#[must_use = "iterators are lazy and do nothing unless consumed"]
pub struct RawPathParamsIter<'params> {
    inner: slice::Iter<'params, RawPathParam>,
}

impl<'params> Iterator for RawPathParamsIter<'params> {
    type Item = (&'params str, &'params str);

    fn next(&mut self) -> Option<Self::Item> {
        self.inner
            .next()
            .map(|param| (param.name.as_ref(), param.value.raw()))
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        self.inner.size_hint()
    }
}

impl DoubleEndedIterator for RawPathParamsIter<'_> {
    fn next_back(&mut self) -> Option<Self::Item> {
        self.inner
            .next_back()
            .map(|param| (param.name.as_ref(), param.value.raw()))
    }
}

impl ExactSizeIterator for RawPathParamsIter<'_> {}
impl FusedIterator for RawPathParamsIter<'_> {}

#[derive(Debug, Clone)]
struct RawPathParam {
    name: Arc<str>,
    value: RawPathParamValue,
}

#[derive(Debug, Clone)]
enum RawPathParamValue {
    Segment(Box<str>),
    CatchAll {
        raw: Box<str>,
        segments: Box<[Box<str>]>,
    },
}

impl RawPathParamValue {
    fn raw(&self) -> &str {
        match self {
            Self::Segment(value) => value,
            Self::CatchAll { raw, .. } => raw,
        }
    }
}

#[derive(Debug, Clone)]
pub(crate) struct RawPathParamSpec {
    name: Arc<str>,
    kind: RawPathParamKind,
}

impl RawPathParamSpec {
    pub(crate) fn segment(name: Arc<str>) -> Self {
        Self {
            name,
            kind: RawPathParamKind::Segment,
        }
    }

    pub(crate) fn catch_all(name: Arc<str>) -> Self {
        Self {
            name,
            kind: RawPathParamKind::CatchAll,
        }
    }
}

#[derive(Debug, Clone, Copy)]
enum RawPathParamKind {
    Segment,
    CatchAll,
}

fn decode(value: &str) -> Box<str> {
    percent_decode_str(value)
        .decode_utf8_lossy()
        .into_owned()
        .into_boxed_str()
}

/// A guard that limits [`PathParam::path_param`] to being called through the
/// [`path_param`] free function.
///
/// It cannot be constructed outside this crate, so the only way to invoke the
/// trait method is via [`path_param`].
#[doc(hidden)]
#[derive(Debug)]
pub struct PathParamSealed(());

impl PathParamSealed {
    pub(crate) fn new() -> Self {
        Self(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn params<'pairs>(
        pairs: impl IntoIterator<Item = (&'static str, bool, &'pairs str)>,
    ) -> RawPathParams {
        RawPathParams::from_pairs(pairs.into_iter().map(|(name, catch_all, value)| {
            let name = Arc::from(name);
            let param = if catch_all {
                RawPathParamSpec::catch_all(name)
            } else {
                RawPathParamSpec::segment(name)
            };
            (param, value)
        }))
    }

    fn segments<'params>(
        params: &'params RawPathParams,
        name: &str,
    ) -> Option<CatchAllSegments<'params>> {
        match params.find(name) {
            Some(RawPathParamValue::CatchAll { segments, .. }) => {
                Some(CatchAllSegments::new(segments))
            }
            Some(RawPathParamValue::Segment(_)) | None => None,
        }
    }

    #[test]
    fn decodes_a_single_segment() {
        let params = params([("id", false, "a%20b")]);

        assert_eq!(params.find("id").map(RawPathParamValue::raw), Some("a b"));
    }

    #[test]
    fn keeps_a_catch_all_tail_raw() {
        let params = params([("path", true, "guides/getting%2Fstarted")]);

        assert_eq!(
            params.find("path").map(RawPathParamValue::raw),
            Some("guides/getting%2Fstarted")
        );
        assert_eq!(
            segments(&params, "path").unwrap().collect::<Vec<_>>(),
            ["guides", "getting/started"]
        );
    }

    #[test]
    fn reads_a_single_segment_catch_all() {
        let params = params([("path", true, "readme.md")]);

        assert_eq!(
            segments(&params, "path").unwrap().collect::<Vec<_>>(),
            ["readme.md"]
        );
    }

    #[test]
    fn missing_parameter_is_absent() {
        let params = params([("id", false, "42")]);

        assert!(params.find("slug").is_none());
        assert!(segments(&params, "slug").is_none());
    }

    #[test]
    fn iterates_over_every_pair() {
        let params = params([("id", false, "42"), ("path", true, "a/b")]);

        assert_eq!(
            params.iter().collect::<Vec<_>>(),
            [("id", "42"), ("path", "a/b")]
        );
    }

    #[test]
    fn segments_count_without_consuming() {
        let params = params([("path", true, "a/b/c")]);
        let segments = segments(&params, "path").unwrap();

        assert_eq!(segments.len(), 3);
        assert_eq!(segments.rev().collect::<Vec<_>>(), ["c", "b", "a"]);
    }
}
