[package]
name = "topcoat-vercel"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
readme = "README.md"
default-run = "topcoat-vercel"

[features]
default = ["cli"]
cli = [
	"dep:anyhow",
	"dep:clap",
	"dep:serde",
	"dep:serde_json",
	"dep:topcoat-asset",
	"dep:topcoat-core",
]

[[bin]]
name = "topcoat-vercel"
path = "src/bin/topcoat_vercel.rs"
required-features = ["cli"]

[dependencies]
topcoat-asset = { workspace = true, optional = true, features = ["bundler"] }
topcoat-core = { workspace = true, optional = true, features = ["build"] }
topcoat-router.workspace = true

anyhow = { workspace = true, optional = true }
clap = { workspace = true, optional = true, features = ["derive"] }
http-body-util.workspace = true
serde = { workspace = true, optional = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
tokio-stream.workspace = true
vercel_runtime.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
