use topcoat_core::runtime::{context::Cx, error::Error};

use crate::runtime::View;

/// A renderable component.
///
/// Implementations are usually generated by Topcoat's component macro. Manual
/// implementations receive the current context and child content, then return
/// a rendered [`View`] or an error.
pub trait Component {
    /// Renders this component with the provided context and child view.
    fn render(self, cx: &Cx, child: View) -> impl Future<Output = Result<View, Error>> + Send;
}
