/// A props struct with a generated typestate builder.
///
/// Implemented by [`#[derive(Props)]`][derive]. The derive also generates an
/// inherent `builder()` function on the struct, so this trait only needs to be
/// in scope when the builder is constructed generically.
///
/// [derive]: derive.Props.html
pub trait Props {
    /// The builder type in its initial state, with no properties set.
    type Builder;

    /// Returns a builder with no properties set.
    fn builder() -> Self::Builder;
}

/// Typestate marker for a required property that has been set.
///
/// Used as a generic argument of builders generated by
/// [`#[derive(Props)]`][derive]. The `build()` method is only available once
/// every required property's marker is [`Set`].
///
/// [derive]: derive.Props.html
pub struct Set;

/// Typestate marker for a required property that has not been set yet.
///
/// Used as a generic argument of builders generated by
/// [`#[derive(Props)]`][derive]. Builders start with every required property's
/// marker at [`Unset`].
///
/// [derive]: derive.Props.html
pub struct Unset;
