/// Declares the stylesheet generated by the build script as an asset.
///
/// The macro returns a `topcoat::asset::Asset`, which renders as the URL of
/// the stylesheet. Use it as the `href` of a `<link>` element:
///
/// ```rust,ignore
/// view! {
///     <link rel="stylesheet" href=(tailwind::stylesheet!())>
/// }
/// ```
///
/// It expands to:
///
/// ```rust,ignore
/// topcoat::asset::asset!(concat!(env!("OUT_DIR"), "/tailwind.css"))
/// ```
///
/// This is the default output file of `BuildConfig::render`. If your build
/// script sets a different `output`, declare that file with `asset!`
/// instead. The macro reads `OUT_DIR`, so the crate that calls it must have
/// a build script.
#[macro_export]
macro_rules! stylesheet {
    () => {
        ::topcoat::asset::asset!(concat!(env!("OUT_DIR"), "/tailwind.css"))
    };
}
