/// The Tailwind stylesheet generated by the build script, as an asset URL
/// usable as an `href`.
///
/// Expands to
///
/// ```rust,ignore
/// topcoat::asset::asset!(concat!(env!("OUT_DIR"), "/tailwind.css"))
/// ```
///
/// which is the default `output` location of `BuildConfig::render`. When the
/// build script configures a custom `output`, link that file with `asset!`
/// directly instead.
///
/// ```rust,ignore
/// view! {
///     <link rel="stylesheet" href=(tailwind::stylesheet!())>
/// }
/// ```
#[macro_export]
macro_rules! stylesheet {
    () => {
        ::topcoat::asset::asset!(concat!(env!("OUT_DIR"), "/tailwind.css"))
    };
}
