/// The Tailwind stylesheet generated by the build script, as an asset URL
/// usable as an `href`.
///
/// Uses the default output of `BuildConfig::render`. If the build script
/// configures a different output, refer to that file with `asset!` instead.
///
/// ```rust,ignore
/// view! {
///     <link rel="stylesheet" href=(tailwind::stylesheet!())>
/// }
/// ```
#[macro_export]
macro_rules! stylesheet {
    () => {
        ::topcoat::asset::asset!(concat!(env!("OUT_DIR"), "/tailwind.css"))
    };
}
