/// A props struct with a generated typestate builder.
///
/// Implemented by [`#[derive(Props)]`][derive]. The derive also adds an
/// inherent `builder()` function to the struct, so this trait only needs to
/// be in scope for code that creates the builder generically.
///
/// [derive]: https://docs.rs/topcoat/latest/topcoat/view/derive.Props.html
pub trait Props {
    /// The builder type in its initial state, with no properties set.
    type Builder;

    /// Returns a builder with no properties set.
    fn builder() -> Self::Builder;
}

/// Typestate marker for a required property that has been set.
///
/// Builders generated by [`#[derive(Props)]`][derive] track each required
/// property in a generic argument. Before the property is set, the argument
/// is a generated marker type named after the property. Calling the
/// property's setter changes it to [`Set`].
///
/// [derive]: https://docs.rs/topcoat/latest/topcoat/view/derive.Props.html
pub struct Set;

/// Implemented by typestate markers of properties that have been set.
///
/// `build()` on a generated builder requires the marker of every required
/// property to implement this trait. The markers of unset properties are
/// named after their property, so the compile error names the missing
/// property.
#[diagnostic::on_unimplemented(
    message = "missing required property `{Self}`",
    label = "the property `{Self}` was not set",
    note = "every property without `#[default]` must be set before calling `build()`"
)]
pub trait IsSet {}

impl IsSet for Set {}
