//! Generates a registry's `registry.toml` manifest from a programmatic
//! description of its components.
//!
//! Rather than maintaining `registry.toml` by hand, each registry ships a small
//! binary that declares its components — their names, source files, and
//! dependencies — and calls [`Registry::generate`]. The component *version* is
//! not declared: it is the sha256 of the source file's contents, so any edit to
//! a component bumps its version automatically and projects are told an update
//! is available.
//!
//! ```no_run
//! use std::path::Path;
//! use topcoat_ui::generate::{Component, Registry};
//!
//! let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/topcoat");
//! Registry::new("topcoat")
//!     .component(
//!         Component::new("button", "button.rs")
//!             .dep("kek")
//!             .dep_from("file://../reg2", "gadget"),
//!     )
//!     .component(Component::new("kek", "kek.rs"))
//!     .generate(&dir)
//!     .unwrap();
//! ```

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::registry::{MANIFEST_FILE, MANIFEST_VERSION};

/// The subdirectory of a registry holding the component source files.
const COMPONENTS_DIR: &str = "components";

/// A dependency on another component, declared alongside a [`Component`].
enum Dependency {
    /// A component in the same registry, named directly.
    Same(String),
    /// A component in another registry, identified by that registry's location.
    Other { registry: String, name: String },
}

/// A component to be written into a generated registry manifest. Both the
/// component's name and its source file are declared explicitly — the name is
/// not derived from the file.
pub struct Component {
    name: String,
    file: String,
    dependencies: Vec<Dependency>,
}

impl Component {
    /// Declares a component named `name` whose source is the file `file` inside
    /// the registry's `components/` directory.
    pub fn new(name: impl Into<String>, file: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            file: file.into(),
            dependencies: Vec::new(),
        }
    }

    /// Adds a dependency on another component in the same registry.
    pub fn dep(mut self, name: impl Into<String>) -> Self {
        self.dependencies.push(Dependency::Same(name.into()));
        self
    }

    /// Adds a dependency on a component in another registry, named by that
    /// registry's location (a path, `file://` path, or `http(s)://` URL — a
    /// relative `file://` is resolved against this registry's directory).
    pub fn dep_from(mut self, registry: impl Into<String>, name: impl Into<String>) -> Self {
        self.dependencies.push(Dependency::Other {
            registry: registry.into(),
            name: name.into(),
        });
        self
    }
}

/// A registry described in code, ready to emit its `registry.toml`.
pub struct Registry {
    name: String,
    components: Vec<Component>,
}

impl Registry {
    /// Begins describing a registry with the given declared name.
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            components: Vec::new(),
        }
    }

    /// Adds a component to the registry.
    pub fn component(mut self, component: Component) -> Self {
        self.components.push(component);
        self
    }

    /// Writes `registry.toml` into `dir`, hashing each component's source file
    /// (expected at `dir/components/<file>`) to derive its version. Returns the
    /// path of the written manifest.
    pub fn generate(&self, dir: &Path) -> Result<PathBuf, Error> {
        // Sort by name so the output is stable regardless of declaration order.
        let mut components: Vec<&Component> = self.components.iter().collect();
        components.sort_by(|a, b| a.name.cmp(&b.name));

        let mut out = String::new();
        out.push_str(
            "# Generated by this registry's binary. Do not edit by hand.\n\
             # Run `cargo run -p topcoat-ui --bin <registry>-registry --features generate`.\n\
             # Each component's version is the sha256 of its source file.\n\n",
        );
        writeln!(out, "version = {MANIFEST_VERSION}").expect("writing to a String cannot fail");
        writeln!(out, "name = {}", quote(&self.name)).expect("writing to a String cannot fail");

        for component in components {
            let source = format!("{COMPONENTS_DIR}/{}", component.file);
            let path = dir.join(&source);
            let contents = std::fs::read(&path).map_err(|source| Error::Read {
                path: path.clone(),
                source,
            })?;
            let version = format!("sha256:{}", hex(Sha256::digest(&contents).as_ref()));

            out.push('\n');
            writeln!(out, "[components.{}]", component.name).unwrap();
            writeln!(out, "version = {}", quote(&version)).unwrap();
            writeln!(out, "source = {}", quote(&source)).unwrap();
            if !component.dependencies.is_empty() {
                writeln!(out, "dependencies = {}", render_deps(&component.dependencies))
                    .unwrap();
            }
        }

        let manifest = dir.join(MANIFEST_FILE);
        std::fs::write(&manifest, out).map_err(|source| Error::Write {
            path: manifest.clone(),
            source,
        })?;
        Ok(manifest)
    }
}

/// Renders a component's dependency list as an inline TOML array.
fn render_deps(dependencies: &[Dependency]) -> String {
    let items: Vec<String> = dependencies
        .iter()
        .map(|dependency| match dependency {
            Dependency::Same(name) => quote(name),
            Dependency::Other { registry, name } => {
                format!("{{ registry = {}, name = {} }}", quote(registry), quote(name))
            }
        })
        .collect();
    format!("[{}]", items.join(", "))
}

/// Quotes a string as a basic TOML string. The values here (names, paths,
/// hashes) contain no control characters, so escaping quotes and backslashes is
/// sufficient.
fn quote(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// Lowercase hex encoding of a byte slice.
fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(out, "{byte:02x}").expect("writing to a String cannot fail");
    }
    out
}

/// An error generating a registry manifest.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("failed to read component source {path:?}")]
    Read {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to write manifest {path:?}")]
    Write {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}
