[package]
name = "shard"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
futures-core.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "time"] }
topcoat.workspace = true

[lints]
workspace = true
